DI-601 v1.4.0 Variant counts and multiple reports per sample
eastgenomics/eggd_artemis pull request #19
Opened 2024-01-09 13:10 UTC by rklocke

**Changes**
- Adds number of samples released in the links file
- Adds SNV/CNV counts in Excel report if available
  - Removes SNV or CNV report download URLs if no SNVs pass filtering/no CNVs detected
- Allows releasing of multiple SNV and CNV reports per sample (i.e. if reports are separated by clinical indication)
  - Orders SNV and CNV reports by panel (if present) 
  - Names CNV IGV session files for the sample differently (from the naming of the CNV report)
- Updates README to include the correct default URL duration (closes #17)
- Fixes typo in dxapp.json (closes #15)

**Example test jobs**
**Excel report metadata (clinical indications and variant counts) present, reports split per sample by panel**
Job: https://platform.dnanexus.com/panx/projects/Gf1P7jj4j057jX8697VfB2GX/monitor/job/GfKXvPQ4j05F613YkZX6Bvz5

**Excel report metadata (clinical indications and variant counts) present, reports not split per sample by panel**
Job: https://platform.dnanexus.com/panx/projects/Gf1P7jj4j057jX8697VfB2GX/monitor/job/GfKY0G04j055Z47z31Qzv2Vy

**As current set up - Excel report metadata not present, reports not split per sample by panel**
Job: https://platform.dnanexus.com/panx/projects/Gf1P7jj4j057jX8697VfB2GX/monitor/job/GfKYp8Q4j05JpyQBFzG51Z33

2024-01-11 12:07 UTC, jethror1 requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @Addy81 and @rklocke)

___
*[`src/eggd_artemis.py` line 78 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsKLuK8dy-kukr6p66:-NnsKLuK8dy-kukr6p67:b-t0oxg0) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L78)):*
> ```Python
>         file_details = dxpy.bindings.dxdataobject_functions.get_details(
>             report['id']
>         )
> ```

using the `dxpy.DXFile` method is a bit simpler:
```
dxpy.DXFile('file-GfPBgQ04F66y5xx0yBJxJvGg').get_details()
{'clinical_indication': 'R208.1_Inherited breast cancer and ovarian cancer_P', 'included': 1, 'excluded': 65}
```



_Code quote:_
```Python
        file_details = dxpy.bindings.dxdataobject_functions.get_details(
            report['id']
        )
```
___
*[`src/eggd_artemis.py` line 147 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsMweQ6UwM5TQtirDX:-NnsMweQ6UwM5TQtirDY:bkog15z) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L147)):*
> ```Python
>                 sample = data['sample']
>                 clin_ind = list(data['clinical_indications'])[0]
>                 snv_files = data['clinical_indications'][clin_ind]['SNV'][0]
> ```

will these definitely always have one element and not be empty to result in an `IndexError`?



_Code quote:_
```Python
                clin_ind = list(data['clinical_indications'])[0]
                snv_files = data['clinical_indications'][clin_ind]['SNV'][0]
```
___
*[`src/eggd_artemis.py` line 162 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsL2_k0RKin02laLlp:-NnsL2_k0RKin02laLlq:b-jpdt1p) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L162)):*
I think what you're trying to get here is the following right:
```
{
  "sample1": {
      'clinical_indications': {
          'R1.1': {
              'SNV': [...]  
        }
      }
  }
}
```

which I think can be done easier with a nested default dict to set up the 3 levels of dict and a list:
```
>>> d = defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(list))))
>>> d['sample1']['clinical_indications']['R1.1']['SNV'].append('cat')
>>> d
defaultdict(<function <lambda> at 0x10505b4c0>, {'sample1': defaultdict(<function <lambda>.<locals>.<lambda> at 0x104eb3b80>, {'clinical_indications': defaultdict(<function <lambda>.<locals>.<lambda>.<locals>.<lambda> at 0x103f7a4c0>, {'R1.1': defaultdict(<class 'list'>, {'SNV': ['cat']})})})})
```

this means you don't have to keep checking for existing keys at each level (I think its right for what you want), so you should be able to just do:

```
snv_data = defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(list))))

snv_data[sample]['clinical_indications'][clin_ind]['SNV'].append(snv_files)
```



_Code quote:_
```Python
                sample = data['sample']
                clin_ind = list(data['clinical_indications'])[0]
                snv_files = data['clinical_indications'][clin_ind]['SNV'][0]

                # If sample and clinical indication already exists, append SNV
                # file info to the existing list. Otherwise merge to the
                # existing sample dict to add the new clinical indication
                if sample in snv_data:
                    if clin_ind in snv_data[sample].get('clinical_indications'):
                        snv_data[sample][
                            'clinical_indications'
                        ][clin_ind]['SNV'].append(snv_files)

                    else:
                        merge(snv_data[sample], data)
                # If sample doesn't exist just add the data to sample key as is
                else:
                    snv_data[sample] = data
```
___
*[`src/eggd_artemis.py` line 288 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsNRQL93btekWj26-1:-NnsNRQM8zEruoQgQ8NR:b-kpjia5) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L288)):*
if you just want everything after the first occurance in a string this can be done like:

```
>>> sample = 'sample1_R1.1_SNV.xlsx'
>>> sample.split('_', 1)[1].replace('.xlsx', '')
'R1.1_SNV'
```



_Code quote:_
```Python
        cnv_file_ending = ('_').join(
            part for part in report_name.split("_")[1:]
        ).replace('.xlsx', '')
```
___
*[`src/eggd_artemis.py` line 361 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsNhiTCs9Qc6CPBwBD:-NnsNhiTCs9Qc6CPBwBE:bp7cup2) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L361)):*
> ```Python
>         }
> 
>         for future in concurrent.futures.as_completed(concurrent_jobs):
> ```

same comment as before with defaultdict
___
*[`src/eggd_artemis.py` line 836 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsOueO-Tu4SSxu36WF:-NnsOueO-Tu4SSxu36WG:bwcsdt1) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L836)):*
instead of checking for presence, this can be simplified by providing empty dicts as defaults to `get()`:

```
>>> for snv_data in file_data.get('SNV', {}):
...     if snv_data.get(field):
```



_Code quote:_
```Python
                if file_data.get('SNV'):
                    for snv_data in file_data['SNV']:
                        if snv_data.get(field):
```
___
*[`src/eggd_artemis.py` line 845 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsPAwQ6fBWr5Ce3946:-NnsPAwQ6fBWr5Ce3947:bnj7hl0) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L845)):*
> ```Python
>                 if file_data.get('CNV'):
>                     for cnv_data in file_data['CNV']:
>                         if cnv_data.get(field):
> ```

same as above



_Code quote:_
```Python
                if file_data.get('CNV'):
                    for cnv_data in file_data['CNV']:
                        if cnv_data.get(field):
```
___
*[`src/eggd_artemis.py` line 1119 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsPjRI7sgdg_bn3wmM:-NnsPjRI7sgdg_bn3wmN:b-wkrhgm) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L1119)):*
> ```Python
>         if entry['clinical_indications'][clin_ind].get('CNV')
>         for cnv_item in entry['clinical_indications'][clin_ind]['CNV']
>     ]
> ```

I'm all for complex one liners but even this hurts my brain, could you add a comment with an example structure that this is iterating on? Also might be better split up for readability



_Code quote:_
```Python
    session_files = [
        cnv_item.get('cnv_session_fileid')
        for key, entry in all_sample_urls.items()
        for clin_ind in entry.get('clinical_indications')
        if entry['clinical_indications'][clin_ind].get('CNV')
        for cnv_item in entry['clinical_indications'][clin_ind]['CNV']
    ]
```


<!-- Sent from Reviewable.io -->

2024-01-11 15:22 UTC, rklocke reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @Addy81 and @jethror1)

___
*[`src/eggd_artemis.py` line 78 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsKLuK8dy-kukr6p66:-Nnt5-zM9ptV3POSueGI:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L78)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

using the `dxpy.DXFile` method is a bit simpler:
```
dxpy.DXFile('file-GfPBgQ04F66y5xx0yBJxJvGg').get_details()
{'clinical_indication': 'R208.1_Inherited breast cancer and ovarian cancer_P', 'included': 1, 'excluded': 65}
```
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 147 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsMweQ6UwM5TQtirDX:-Nnt5Imp5k5qNb-ybLd0:b-wnrquf) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L147)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

will these definitely always have one element and not be empty to result in an `IndexError`?
</blockquote></details>

Yes, each dict returned by futures will always be information based on one SNV report which will always be within one clinical indication. The clinical indication is obtained from the SNV report metadata or will be 'Unknown' if that info doesn't exist. 
___
*[`src/eggd_artemis.py` line 162 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsL2_k0RKin02laLlp:-Nnt56tl1FuMq1WJ5b-6:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L162)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I think what you're trying to get here is the following right:
```
{
  "sample1": {
      'clinical_indications': {
          'R1.1': {
              'SNV': [...]  
        }
      }
  }
}
```

which I think can be done easier with a nested default dict to set up the 3 levels of dict and a list:
```
>>> d = defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(list))))
>>> d['sample1']['clinical_indications']['R1.1']['SNV'].append('cat')
>>> d
defaultdict(<function <lambda> at 0x10505b4c0>, {'sample1': defaultdict(<function <lambda>.<locals>.<lambda> at 0x104eb3b80>, {'clinical_indications': defaultdict(<function <lambda>.<locals>.<lambda>.<locals>.<lambda> at 0x103f7a4c0>, {'R1.1': defaultdict(<class 'list'>, {'SNV': ['cat']})})})})
```

this means you don't have to keep checking for existing keys at each level (I think its right for what you want), so you should be able to just do:

```
snv_data = defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(list))))

snv_data[sample]['clinical_indications'][clin_ind]['SNV'].append(snv_files)
```
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 288 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsNRQL93btekWj26-1:-Nnt57X23SSJmimo1M0U:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L288)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

if you just want everything after the first occurance in a string this can be done like:

```
>>> sample = 'sample1_R1.1_SNV.xlsx'
>>> sample.split('_', 1)[1].replace('.xlsx', '')
'R1.1_SNV'
```
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 361 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsNhiTCs9Qc6CPBwBD:-Nnt59W73T2fT31ILiqu:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L361)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

same comment as before with defaultdict
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 836 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsOueO-Tu4SSxu36WF:-Nnt6Hi60pDecubdtyFs:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L836)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

instead of checking for presence, this can be simplified by providing empty dicts as defaults to `get()`:

```
>>> for snv_data in file_data.get('SNV', {}):
...     if snv_data.get(field):
```
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 845 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsPAwQ6fBWr5Ce3946:-Nnt6JHP9BhtCaDsXcmb:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L845)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 1119 at r2](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-NnsPjRI7sgdg_bn3wmM:-Nnt6NFEDCCGMn1wfvUf:bgtzsjf) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/36e83538b03f58186d28fe8ef53ec1b11edab1c1/src/eggd_artemis.py#L1119)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I'm all for complex one liners but even this hurts my brain, could you add a comment with an example structure that this is iterating on? Also might be better split up for readability
</blockquote></details>

agree, added an example comment and changed to a for loop


<!-- Sent from Reviewable.io -->

2024-01-12 09:45 UTC, jethror1 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @Addy81)



<!-- Sent from Reviewable.io -->

2024-01-12 13:28 UTC, Addy81 approved these changes
All looks good, excellent work!

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/19#-:-NnxqxA1DL93pa7MiQG5:b-ahrla3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rklocke)



<!-- Sent from Reviewable.io -->

2024-01-12 13:31 UTC, merged