v1.5.0 - Read in excluded regions file
eastgenomics/eggd_artemis pull request #27
Opened 2024-06-14 13:32 UTC by growland2

- add function to read in excluded regions file
- modify remove_url_if_variant_count_is_zero() function to remove annotated excluded regions dataframe if there are 0 excluded regions

2024-06-14 13:32 UTC, pep8speaks commented
Hello @growland2! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`src/eggd_artemis.py`](https://github.com/eastgenomics/eggd_artemis/blob/5887c963fe60c079da9144c9da44a482fb52421e/src/eggd_artemis.py):

> [Line 791:80](https://github.com/eastgenomics/eggd_artemis/blob/5887c963fe60c079da9144c9da44a482fb52421e/src/eggd_artemis.py#L791): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)

2024-06-14 15:42 UTC, rklocke requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27)* status: all files reviewed, 6 unresolved discussions (waiting on @growland2)

___
*[`src/eggd_artemis.py` line 256 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27#-O-MHNrl3UPg_dnZ-_7a:-O-MHNrl3UPg_dnZ-_7b:bnl556l) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/5887c963fe60c079da9144c9da44a482fb52421e/src/eggd_artemis.py#L256)):*
> ```Python
>                             'CNV variant report': 'file-OP',
>                             'CNV calls for IGV': {'$dnanexus_link': 'file-LM'},
>                             'CNV count': 0,
> ```

can you add the 'CNV excluded regions' to this clinical indication in the example too?
___
*[`src/eggd_artemis.py` line 622 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27#-O-MLiX-3Kh8ipeg9q1f:-O-MLiX-3Kh8ipeg9q1g:bnyn4ld) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/5887c963fe60c079da9144c9da44a482fb52421e/src/eggd_artemis.py#L622)):*
> ```Python
>     )
> 
>     df = pd.read_csv(file, sep="\t", header=0)
> ```

Are we sure that the file will always have the header line? I assume so but may be worth having a quick look at how the annotate excluded regions app works to be sure
___
*[`src/eggd_artemis.py` line 742 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27#-O-MOatX7vqlZ7Q9lVLW:-O-MOatX7vqlZ7Q9lVLX:b-50sk97) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/5887c963fe60c079da9144c9da44a482fb52421e/src/eggd_artemis.py#L742)):*
> ```Python
> 
> 
> def remove_unecessary_outputs(
> ```

this is really pedantic but missing an n in unnecessary
___
*[`src/eggd_artemis.py` line 790 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27#-O-MMY3HDd1Wf43clOly:-O-MMY3HDd1Wf43clOlz:b-5oq3nl) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/5887c963fe60c079da9144c9da44a482fb52421e/src/eggd_artemis.py#L790)):*
> ```Python
>                         if file.get('CNV count') == '0':
>                             file['cnv_url'] = 'No CNVs detected'
>                     if len(file.get('cnv_excluded_regions_df')) == 0:
> ```

I think it would be nicer to use `df.empty` to check if the dataframe is empty (only contains header line) rather than len:



_Code snippet:_
```Python
if file.get('cnv_excluded_regions_df').empty:
```
___
*[`src/eggd_artemis.py` line 1142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27#-O-MOiZ1AmM8LFNZsEhQ:-O-MOiZ1AmM8LFNZsEhR:b-bo1o97) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/5887c963fe60c079da9144c9da44a482fb52421e/src/eggd_artemis.py#L1142)):*
> ```Python
> 
>     # Remove download URLs for reports with no variants in and remove
>     # excluded regions dataframe if no excldued regions
> ```

excluded typo
___
*[`src/eggd_artemis.py` line 1175 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27#-O-MPS3J24Las_07j9IS:-O-MPS3J24Las_07j9IT:b-tw5bvi) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/5887c963fe60c079da9144c9da44a482fb52421e/src/eggd_artemis.py#L1175)):*
> ```Python
>                     'snv_url': '=HYPERLINK("hyperlink", "hyperlink"),
>                 }],
>                 'CNV': [{
> ```

does this need updating to include the excluded regions df?


<!-- Sent from Reviewable.io -->

2024-06-18 09:03 UTC, growland2 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27)* status: all files reviewed, 6 unresolved discussions (waiting on @rklocke)

___
*[`src/eggd_artemis.py` line 256 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27#-O-MHNrl3UPg_dnZ-_7a:-O-eT4fp-a9p7Qt6cch7:b-wqnw6c) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/5887c963fe60c079da9144c9da44a482fb52421e/src/eggd_artemis.py#L256)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

can you add the 'CNV excluded regions' to this clinical indication in the example too?
</blockquote></details>

I think it's already there (line 257)
___
*[`src/eggd_artemis.py` line 622 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27#-O-MLiX-3Kh8ipeg9q1f:-O-eWays7GKlQQma-uS8:b-sp39p) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/5887c963fe60c079da9144c9da44a482fb52421e/src/eggd_artemis.py#L622)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

Are we sure that the file will always have the header line? I assume so but may be worth having a quick look at how the annotate excluded regions app works to be sure
</blockquote></details>

Checked app and the excluded regions file should always have a header [(see line 146 in annotate_excluded_panel.py)](https://github.com/eastgenomics/eggd_annotate_excluded_regions/blob/ff1994813d89cf9e70781ae9c73ed8f8d9a4e6b5/resources/home/dnanexus/annotate_excluded_panel.py#L146)
___
*[`src/eggd_artemis.py` line 742 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27#-O-MOatX7vqlZ7Q9lVLW:-O-eZ8LZ9gOc1-apHdKo:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/5887c963fe60c079da9144c9da44a482fb52421e/src/eggd_artemis.py#L742)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

this is really pedantic but missing an n in unnecessary
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 790 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27#-O-MMY3HDd1Wf43clOly:-O-eZH4TDgBk1VJwgfNw:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/5887c963fe60c079da9144c9da44a482fb52421e/src/eggd_artemis.py#L790)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

I think it would be nicer to use `df.empty` to check if the dataframe is empty (only contains header line) rather than len:
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 1142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27#-O-MOiZ1AmM8LFNZsEhQ:-O-eZQL51Qp9PCVbrA1m:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/5887c963fe60c079da9144c9da44a482fb52421e/src/eggd_artemis.py#L1142)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

excluded typo
</blockquote></details>

Done.
___
*[`src/eggd_artemis.py` line 1175 at r1](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27#-O-MPS3J24Las_07j9IS:-O-e_N9i9Mv4GVWaOkt4:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_artemis/blob/5887c963fe60c079da9144c9da44a482fb52421e/src/eggd_artemis.py#L1175)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

does this need updating to include the excluded regions df?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-18 09:10 UTC, rklocke approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_artemis/27)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @growland2)



<!-- Sent from Reviewable.io -->

2024-06-18 09:10 UTC, merged